<a href="https://colab.research.google.com/github/MeenTers/KKU_data_mining/blob/master/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Function

In [6]:
import pandas as pd
import os
import numpy as np
import datetime as dt

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
path = '/content/drive/My Drive/SIST'

In [9]:
data_path = os.path.join(path,'A2.xlsx')

# DataFrame

In [5]:
data1 = pd.read_excel(data_path,sheet_name='Year 2009-2010')
data1.head()

Invoice StockCode  ... Customer ID         Country
0  489434     85048  ...     13085.0  United Kingdom
1  489434    79323P  ...     13085.0  United Kingdom
2  489434    79323W  ...     13085.0  United Kingdom
3  489434     22041  ...     13085.0  United Kingdom
4  489434     21232  ...     13085.0  United Kingdom

[5 rows x 8 columns]

In [10]:
data1.count()

Invoice        525461
StockCode      525461
Description    522533
Quantity       525461
InvoiceDate    525461
Price          525461
Customer ID    417534
Country        525461
dtype: int64

In [11]:
data2 = pd.read_excel(data_path,sheet_name='Year 2010-2011')
data2.head()

Invoice StockCode  ... Customer ID         Country
0  536365    85123A  ...     17850.0  United Kingdom
1  536365     71053  ...     17850.0  United Kingdom
2  536365    84406B  ...     17850.0  United Kingdom
3  536365    84029G  ...     17850.0  United Kingdom
4  536365    84029E  ...     17850.0  United Kingdom

[5 rows x 8 columns]

In [12]:
data2.count()

Invoice        541910
StockCode      541910
Description    540456
Quantity       541910
InvoiceDate    541910
Price          541910
Customer ID    406830
Country        541910
dtype: int64

In [110]:
all_table = pd.concat([data1,data2])
all_table

Invoice StockCode  ... Customer ID         Country
0       489434     85048  ...     13085.0  United Kingdom
1       489434    79323P  ...     13085.0  United Kingdom
2       489434    79323W  ...     13085.0  United Kingdom
3       489434     22041  ...     13085.0  United Kingdom
4       489434     21232  ...     13085.0  United Kingdom
...        ...       ...  ...         ...             ...
541905  581587     22899  ...     12680.0          France
541906  581587     23254  ...     12680.0          France
541907  581587     23255  ...     12680.0          France
541908  581587     22138  ...     12680.0          France
541909  581587      POST  ...     12680.0          France

[1067371 rows x 8 columns]

# Clean Data

In [111]:
all_table.isnull().any()

Invoice        False
StockCode      False
Description     True
Quantity       False
InvoiceDate    False
Price          False
Customer ID     True
Country        False
dtype: bool

In [112]:
all_table.dropna(subset=['Customer ID'],inplace=True)
all_table

Invoice StockCode  ... Customer ID         Country
0       489434     85048  ...     13085.0  United Kingdom
1       489434    79323P  ...     13085.0  United Kingdom
2       489434    79323W  ...     13085.0  United Kingdom
3       489434     22041  ...     13085.0  United Kingdom
4       489434     21232  ...     13085.0  United Kingdom
...        ...       ...  ...         ...             ...
541905  581587     22899  ...     12680.0          France
541906  581587     23254  ...     12680.0          France
541907  581587     23255  ...     12680.0          France
541908  581587     22138  ...     12680.0          France
541909  581587      POST  ...     12680.0          France

[824364 rows x 8 columns]

In [113]:
all_table.isnull().any()

Invoice        False
StockCode      False
Description    False
Quantity       False
InvoiceDate    False
Price          False
Customer ID    False
Country        False
dtype: bool

# UK Data

In [132]:
uk_data = all_table[all_table['Country']=='United Kingdom']
uk_data = uk_data[uk_data['Price'] > 0 ]
uk_data = uk_data[uk_data['Quantity'] > 0 ]
uk_data

Invoice StockCode  ... Customer ID         Country
0       489434     85048  ...     13085.0  United Kingdom
1       489434    79323P  ...     13085.0  United Kingdom
2       489434    79323W  ...     13085.0  United Kingdom
3       489434     22041  ...     13085.0  United Kingdom
4       489434     21232  ...     13085.0  United Kingdom
...        ...       ...  ...         ...             ...
541889  581585     22466  ...     15804.0  United Kingdom
541890  581586     22061  ...     13113.0  United Kingdom
541891  581586     23275  ...     13113.0  United Kingdom
541892  581586     21217  ...     13113.0  United Kingdom
541893  581586     20685  ...     13113.0  United Kingdom

[725250 rows x 8 columns]

In [128]:
uk_data[uk_data['Price'] < 0 ]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

# Monetary

In [133]:
uk_data['Total'] = uk_data['Price'] * uk_data['Quantity']
uk_data

Invoice StockCode  ...         Country  Total
0       489434     85048  ...  United Kingdom   83.4
1       489434    79323P  ...  United Kingdom   81.0
2       489434    79323W  ...  United Kingdom   81.0
3       489434     22041  ...  United Kingdom  100.8
4       489434     21232  ...  United Kingdom   30.0
...        ...       ...  ...             ...    ...
541889  581585     22466  ...  United Kingdom   23.4
541890  581586     22061  ...  United Kingdom   23.6
541891  581586     23275  ...  United Kingdom   30.0
541892  581586     21217  ...  United Kingdom  214.8
541893  581586     20685  ...  United Kingdom   70.8

[725250 rows x 9 columns]

In [134]:
monetary_uk = uk_data[['Customer ID','Total']]
monetary_uk.head()

Customer ID  Total
0      13085.0   83.4
1      13085.0   81.0
2      13085.0   81.0
3      13085.0  100.8
4      13085.0   30.0

In [135]:
monetary_uk = monetary_uk.groupby('Customer ID').sum()
monetary_uk

Total
Customer ID          
12346.0      77556.46
12608.0        415.79
12745.0        723.85
12746.0        254.55
12747.0       9276.54
...               ...
18283.0       2736.65
18284.0        461.68
18285.0        427.00
18286.0       1296.43
18287.0       4182.99

[5350 rows x 1 columns]

# Recency

In [141]:
recency_uk  = uk_data[['Customer ID','InvoiceDate']]
maximum = max(recency_uk['InvoiceDate'])
maximum

Timestamp('2011-12-09 12:49:00')

In [145]:
# Filtering data for customerid and invoice_date
recency_uk  = uk_data[['Customer ID','InvoiceDate']]

# Finding max data
#maximum = max(recency_uk['InvoiceDate'])
df_max_purchase = uk_data.groupby('Customer ID').InvoiceDate.max().reset_index()
# Adding one more day to the max data, so that the max date will have 1 as the difference and not zero.
maximum = maximum + pd.DateOffset(days=1)
recency_uk['different'] = maximum - recency_uk['InvoiceDate']
recency_uk

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


Customer ID         InvoiceDate         different
0           13085.0 2009-12-01 07:45:00 739 days 05:04:00
1           13085.0 2009-12-01 07:45:00 739 days 05:04:00
2           13085.0 2009-12-01 07:45:00 739 days 05:04:00
3           13085.0 2009-12-01 07:45:00 739 days 05:04:00
4           13085.0 2009-12-01 07:45:00 739 days 05:04:00
...             ...                 ...               ...
541889      15804.0 2011-12-09 12:31:00   1 days 00:18:00
541890      13113.0 2011-12-09 12:49:00   1 days 00:00:00
541891      13113.0 2011-12-09 12:49:00   1 days 00:00:00
541892      13113.0 2011-12-09 12:49:00   1 days 00:00:00
541893      13113.0 2011-12-09 12:49:00   1 days 00:00:00

[725250 rows x 3 columns]

In [146]:
uk_cus = recency.groupby('Customer ID')
uk_cus['different'].min()

Customer ID
12346.0   326 days 02:48:00
12608.0   405 days 02:00:00
12745.0   487 days 02:35:00
12746.0   541 days 02:08:00
12747.0     2 days 22:15:00
                 ...       
18283.0     4 days 00:47:00
18284.0   432 days 01:16:00
18285.0   661 days 02:25:00
18286.0   477 days 00:52:00
18287.0    43 days 03:20:00
Name: different, Length: 5350, dtype: timedelta64[ns]

In [147]:
#Dataframe merging by recency
uk_recen = pd.DataFrame(recency_uk.groupby('Customer ID').different.min())
uk_recen = uk_recen.reset_index()
uk_recen.columns = ['Customer ID', 'Recency']
uk_recen.head()

Customer ID           Recency
0      12346.0 326 days 02:48:00
1      12608.0 405 days 02:00:00
2      12745.0 487 days 02:35:00
3      12746.0 541 days 02:08:00
4      12747.0   2 days 22:15:00

# Frequency

In [148]:
frequency_uk = uk_data[['Customer ID', 'Invoice']]

In [149]:
# Getting the count of orders made by each customer based on customer ID.
freq_uk = frequency_uk.groupby('Customer ID').Invoice.count()
freq_uk = pd.DataFrame(freq_uk)
freq_uk = freq_uk.reset_index()
freq_uk.columns = ['Customer ID', 'Frequency']
freq_uk.head()

Customer ID  Frequency
0      12346.0         34
1      12608.0         16
2      12745.0         22
3      12746.0         17
4      12747.0        257

# RFM combined DataFrame

In [157]:
#Combining all recency, frequency and monetary parameters
RFM_uk = freq_uk.merge(monetary_uk, on = 'Customer ID')
RFM_uk = RFM_uk.merge(uk_recen, on = 'Customer ID')
RFM_uk

Customer ID  Frequency     Total           Recency
0         12346.0         34  77556.46 326 days 02:48:00
1         12608.0         16    415.79 405 days 02:00:00
2         12745.0         22    723.85 487 days 02:35:00
3         12746.0         17    254.55 541 days 02:08:00
4         12747.0        257   9276.54   2 days 22:15:00
...           ...        ...       ...               ...
5345      18283.0        986   2736.65   4 days 00:47:00
5346      18284.0         28    461.68 432 days 01:16:00
5347      18285.0         12    427.00 661 days 02:25:00
5348      18286.0         67   1296.43 477 days 00:52:00
5349      18287.0        155   4182.99  43 days 03:20:00

[5350 rows x 4 columns]

# K-means

In [158]:
from sklearn.cluster import KMeans

In [159]:
def my_kmean(X):
    KMclust = KMeans(n_clusters=3,random_state=10)
    KMclust.fit(X)
    label = KMclust.predict(X)
    return label

In [163]:
kmeans_recen = my_kmean(RFM_uk[['Recency']])
kmeans_recen

array([1, 1, 2, ..., 2, 1, 0], dtype=int32)

In [164]:
kmeans_total = my_kmean(RFM_uk[['Total']])
kmeans_total

array([1, 0, 0, ..., 0, 0, 0], dtype=int32)

In [165]:
kmeans_freq = my_kmean(RFM_uk[['Frequency']])
kmeans_freq

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [166]:
RFM_uk['Group of Frequency'] = kmeans_freq
RFM_uk['Group of Total'] = kmeans_total 
RFM_uk['Group of Recency'] = kmeans_recen
RFM_uk

Customer ID  Frequency  ...  Group of Total Group of Recency
0         12346.0         34  ...               1                1
1         12608.0         16  ...               0                1
2         12745.0         22  ...               0                2
3         12746.0         17  ...               0                2
4         12747.0        257  ...               0                0
...           ...        ...  ...             ...              ...
5345      18283.0        986  ...               0                0
5346      18284.0         28  ...               0                1
5347      18285.0         12  ...               0                2
5348      18286.0         67  ...               0                1
5349      18287.0        155  ...               0                0

[5350 rows x 7 columns]

# Definition of Group K-mean

In [171]:
def mygroupby(x,y):
    values = RFM_uk.groupby(x)[y].describe()
    return values

In [172]:
mygroupby('Group of Frequency','Frequency')

count         mean          std  ...     50%     75%      max
Group of Frequency                                    ...                         
0                   5045.0    86.513181    97.064097  ...    48.0   117.0    461.0
1                      5.0  7245.800000  3346.006157  ...  6566.0  7228.0  12890.0
2                    300.0   841.873333   454.568005  ...   702.0   986.0   3362.0

[3 rows x 8 columns]

In [174]:
mygroupby('Group of Total','Total')

count           mean  ...        75%        max
Group of Total                         ...                      
0               5319.0    2111.073560  ...    2155.40   45179.10
1                 30.0   96184.186733  ...  118163.85  246973.09
2                  1.0  608821.650000  ...  608821.65  608821.65

[3 rows x 8 columns]

In [175]:
mygroupby('Group of Recency','Recency')

count  ...               max
Group of Recency        ...                  
0                 3263  ... 202 days 02:20:00
1                 1382  ... 477 days 03:10:00
2                  705  ... 739 days 02:00:00

[3 rows x 8 columns]