<a href="https://colab.research.google.com/github/MeenTers/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [160]:
import numpy as np

##numpy array

In [161]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [162]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [163]:
np2.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [164]:
np2[0,:]

array([1, 2])

## HW 6 สร้าง Distance matrix (Euclidean) ของ np2  โดย
## สร้าง Function สำหรับคำนวณ  Euclidean Distance
def Euclidean(data1,data2): 
    process
return dist

In [165]:
def Euclidean(data1,data2):
    distX = pow((data1[0]-data2[0]),2)
    distY = pow((data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [166]:
dist_math1 = np.zeros((4,4))
dist_math1


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [167]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

In [168]:
import math

In [169]:
def Manhattan(data1,data2):
    distX = abs(data1[0] - data2[0])
    distY = abs(data1[1] - data2[1])
    return distX + distY

In [170]:
Manhattan(np2[0,:],np2[1,:])

5

In [171]:
dist_mat = np.zeros((4,4))


In [172]:
for i in range(4):
    for j in range(4):
        dist_mat[i,j] = Manhattan(np2[i,:],np2[j,:])
dist_mat

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [173]:
np2.shape

(4, 2)

## Distance of nominal or categorical features

###(extra) Python data structure(Dictionary)

In [174]:
d_A = {'a':1,2:3,3:5,'cat':6}

In [175]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [176]:
d_A['cat']

6

In [177]:
d_A['dog'] = [1,2,3,4,5]

In [178]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [179]:
  import pandas as pd

In [180]:
data_dict = {'color':['red','red','green'],  #color = {'red','green','blue'}
             'status':['single','married','single']}  #status = {'single','married','divo'}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [181]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

#categorical feature distance method#1

In [182]:
list(data_pd.iloc[0,:])

['red', 'single']

In [183]:
def meth1_dist(data1,data2):
    N=0
    print (f' data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
        print(f'feature1 of data1 is {data1[i]},feature1 os data2 is {data2[i]}')
        if data1[i] != data2[i]:
           N = N+1
           print(f'{data1[i]} is not equal {data2[i]} : update({N})')
        else:
            print(f' {data1[i]} is equal {data2[i]}')
    return N/len(data1)

In [184]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

 data1 is ['red', 'single'] and data2 is ['red', 'married']
feature1 of data1 is red,feature1 os data2 is red
 red is equal red
feature1 of data1 is single,feature1 os data2 is married
single is not equal married : update(1)


0.5

 ## HW7 calculate  distance metrix od data_pd using meth_dist()

## categorical feature distance method#2

In [185]:
data_pd_binary = pd.get_dummies(data_pd)
data_pd_binary

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

In [186]:
def binary_sym_dist(data1,data2):
    q = 0
    rs = 0
    t = 0
    for i in range(len(data1)):
        if data1[i] == data2[i]:
           if data1[i] == 1:
              q = q + 1
        else:
            t = t + 1
        if data1[i] != data2[i]:
           rs = rs + 1
    return (rs)/(q+rs+t)



In [187]:
binary_sym_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

0.5

In [188]:
dist_math2 = np.zeros((3,3))
dist_math2 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [193]:
for i in range(3):
    for j in range(3):
        dist_math2[i,j] = binary_sym_dist(list(data_pd.iloc[i,:]),list(data_pd.iloc[j,:]))
dist_math2

ZeroDivisionError: ignored

## HW8 calculate distance metrix of data_pd_binary using data_pd_binary dist()

In [191]:
binary_sym_dist1 = np.zeros((3,3))
binary_sym_dist1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [192]:
for i in range(3):
    for j in range(3):
        binary_sym_dist1[i,j] = binary_sym_dist(list(data_pd_binary.iloc[i,:]),list(data_pd_binary.iloc[j,:]))
binary_sym_dist1

array([[0. , 0.4, 0.4],
       [0.4, 0. , 0.5],
       [0.4, 0.5, 0. ]])